# 在Spring Boot中，配置MySQL数据库的相关信息。
spring:
 application:
   name: lxyuniverse

 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/lxyuniverse
   username: root
   password: admin123
# 设置session失效时间
 session:
   timeout: 86400

server:
  port:  8080
  servlet:
    context-path: /api
# mybatisplus 相关配置
mybatis-plus:
  configuration:
#    1.驼峰的映射规则(自动将驼峰映射为下划线)
    map-underscore-to-camel-case: false
#    2.逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


